---
- name: copy file to remote hosts
  hosts: "{{ host | default('localhost') }}"
  gather_facts: no
  vars:
    filename: "{{ value1 }}"

  tasks:

# check local file  
  - ansible.builtin.stat: 
      checksum_algorithm: sha224
      path: "{{ filename }}"
    delegate_to: localhost
    register: orgfile

# copy file securely    
  - ansible.builtin.copy:
      src: "{{ filename }}"
      dest: "{{ filename }}"
    when: orgfile.stat.exists

